### PR TITLE
Increment versions to 0.1.5.

### PR DESCRIPTION
**Pull request by BranLwyd**
Based on #339.

### CODE REVIEW

**Review by divergentdave — COMMENTED** [review]
The version specified in `janus_client`'s dependency on `janus_core` should be bumped as well, otherwise LGTM.

**Comment by BranLwyd** [comment]
I removed the version specification of `janus_core` in `janus_client`'s Cargo.toml entirely -- AFAICT it's not needed, since we specify a direct path to the crate's source code, which we can do since it's in the same repo. (This also matches how other `janus_foo` crates specify their dependencies on one another.)

**Comment by divergentdave** [comment]
Removing the version won't work, as I now get the following error. The other crates can get away with no version because they all have `publish = false`.

```
$ cargo publish --dry-run -p janus_client
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `janus_core` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```

**Review by tgeoghegan — APPROVED** [review]

**Comment by BranLwyd** [comment]
OK. I specified version `0.1` (rather than `0.1.5`) in an attempt to reduce how often we need to bump this version number.

**Review by divergentdave — APPROVED** [review]

**Pull request merged**
